name: First Workflow
on: workflow_dispatch
jobs:
  first-job: #unlike other keys defined here, not a reserved name
    runs-on: ubuntu-latest
    steps:
     - name: Print greeting
       run: echo "Hello World!"
     - name: Print goodbye
       run: echo "Done - bye!"
